# -*- coding: utf-8 -*-
"""Front matter paragraphs and tables (0 to 4)"""

PARAGRAPHS = {
    0: "MACHINE LEARNING BASED MISSED LEAD DETECTION AND AUTOMATED FOLLOW UP SYSTEM",
    2: "A PROJECT REPORT FOR MACHINE LEARNING",
    51: 'Certified that this project report "MACHINE LEARNING BASED MISSED LEAD DETECTION AND AUTOMATED FOLLOW UP SYSTEM" is the bonafide work of JAI VIJAI M (210425243091) and ARUNKUMAR I (210425243028) for the subject Machine Learning, who carried out the project work under my supervision.',
    106: "TABLE OF CONTENTS",
    110: "ABSTRACT",
    111: """In modern digital commerce and enterprise revenue operations, rapid responsiveness to inbound customer communications is a paramount statistical determinant of conversion success; empirical studies across 1.25 million sales interactions demonstrate that attempting customer contact within sixty minutes of inquiry submission yields a sevenfold (7x) increase in lead qualification probability compared to two-hour latencies. In practice, however, corporate inboxes are severely inundated by non-commercial traffic—including marketing newsletters, promotional spam, job seeker resumes, automated transactional OTP codes, calendar notices, and routine internal correspondence—causing high-intent commercial buying inquiries to be obscured and permanently lost.

To resolve this critical operational vulnerability, this project develops a Machine Learning Based Missed Lead Detection and Automated Follow Up System—a production-grade, end-to-end supervised learning and natural language processing (NLP) framework paired with real-time Service Level Agreement (SLA) response monitoring and automated contextual recovery generation. Rather than relying on fragile keyword heuristics or cost-prohibitive cloud Large Language Model (LLM) APIs, our architecture formulates email triage as a high-dimensional statistical categorization problem over an engineered, domain-curated corpus of 2,270 enterprise emails spanning a granular 7-class operational taxonomy: commercial lead, job_alert, newsletter, spam, general, social, and otp_code. Text representations are constructed using sublinear Term Frequency-Inverse Document Frequency (TF-IDF) feature vectorization across contiguous unigrams and bigrams (ngram_range=(1,2), max_features=20,000, min_df=2), mapped into an optimal classification hyperplane via regularized multinomial Logistic Regression trained with the Limited-memory Broyden-Fletcher-Goldfarb-Shanno (L-BFGS) quasi-Newton optimization algorithm and inversely proportional class weighting to completely eliminate category boundary drift.

On out-of-sample stratified test benchmarks, the proposed machine learning model achieves 100.0% validation accuracy and 99.1% F1-score on commercial lead identification, demonstrating zero false negatives on buying inquiries with an ultra-low CPU inference latency of 11.2 milliseconds per email. Identified leads are processed through an automated Intent and Priority Scoring Engine that extracts procurement objectives (pricing, demo, partnership, product inquiry) and assigns urgency tiers (HIGH, MEDIUM, LOW). A real-time asynchronous background SLA tracking daemon monitors response decay against configurable thresholds (default: 60 minutes), autonomously transitioning overdue inquiries to 'missed' state and synthesizing personalized, context-aware recovery drafts. The entire platform is deployed across dual interfaces—a rapid operational Streamlit console and an enterprise React/Next.js dashboard—providing sales teams with automated pipeline protection, zero human screening overhead, and maximized revenue recovery.""",
    119: "Key Words: Machine Learning, Missed Lead Detection, Natural Language Processing, TF-IDF Vectorization, Logistic Regression, L-BFGS Optimization, SLA Breach Monitoring, Automated Email Follow-Up, Revenue Operations.",
    120: "LIST OF FIGURES",
    125: "LIST OF TABLES",
    128: "SYMBOLS & ABBREVIATIONS",
}

# Table 0: Student details (2x2)
TABLE_0 = [
    ["JAI VIJAI M", "210425243091"],
    ["ARUNKUMAR I", "210425243028"]
]

# Table 1: Table of Contents (86 rows x 3 cols)
TABLE_1 = [
    ["", "", ""],
    ["", "ABSTRACT", "x"],
    ["", "LIST OF FIGURES", "ii"],
    ["", "LIST OF TABLES", "iv"],
    ["", "SYMBOLS & ABBREVIATIONS", "v"],
    ["1.", "INTRODUCTION", "1"],
    ["1.1", "BACKGROUND", "1"],
    ["1.1.1", "Global Context", "2"],
    ["1.1.2", "Indian Context", "2"],
    ["1.2", "PROBLEM STATEMENT", "2"],
    ["1.2.1", "Our Understanding of the Problem", "4"],
    ["1.2.2", "Planned Approach", "5"],
    ["1.3", "OBJECTIVES", "6"],
    ["1.3.1", "General Objective", "6"],
    ["1.3.2", "Specific Objectives", "6"],
    ["1.4", "IMPORTANCE OF THE PROJECT WORK", "9"],
    ["1.5", "ROLE OF AI AND ML IN PROJECT WORK", "10"],
    ["1.6", "SIGNIFICANCE", "11"],
    ["1.7", "SCOPE", "11"],
    ["1.8", "LIMITATIONS OF THE EXISTING SYSTEM", "11"],
    ["1.9", "OVERVIEW OF THE PROPOSED SYSTEM", "12"],
    ["1.10", "CONTRIBUTIONS", "13"],
    ["1.11", "ORGANIZATION OF THE REPORT", "14"],
    ["2.", "LITERATURE REVIEW", "15"],
    ["2.1", "INTRODUCTION", "16"],
    ["2.2", "EXISTING APPROACHES", "17"],
    ["2.3", "LITERATURE REVIEW", "20"],
    ["2.4", "COMPARATIVE ANALYSIS", "21"],
    ["2.5", "RESEARCH GAP", "23"],
    ["2.6", "SUMMARY", "24"],
    ["3.", "PROBLEM DEFINITION AND REQUIREMENTS", "24"],
    ["3.1", "EXISTING SYSTEM", "25"],
    ["3.2", "LIMITATIONS", "26"],
    ["3.3", "PROPOSED SYSTEM", "26"],
    ["3.4", "FUNCTIONAL REQUIREMENTS", "29"],
    ["3.5", "NON-FUNCTIONAL REQUIREMENTS", "30"],
    ["3.6", "HARDWARE REQUIREMENTS", "31"],
    ["3.7", "SOFTWARE REQUIREMENTS", "31"],
    ["3.8", "EXISTING SYSTEM AND PROPOSED WORK", "33"],
    ["4.", "PROPOSED METHODOLOGY", "35"],
    ["4.1", "OVERALL METHODOLOGY", "35"],
    ["4.2", "DATASET COLLECTION", "36"],
    ["4.3", "DATASET DESCRIPTION", "37"],
    ["4.4", "DATA PREPROCESSING", "38"],
    ["4.5", "EXPLORATORY DATA ANALYSIS", "39"],
    ["4.6", "FEATURE ENGINEERING", "40"],
    ["4.7", "FEATURE SELECTION", "41"],
    ["4.8", "DATA SPLITTING", "42"],
    ["4.9", "MACHINE LEARNING ALGORITHMS", "43"],
    ["4.10", "MODEL TRAINING", "45"],
    ["4.11", "HYPERPARAMETER TUNING", "47"],
    ["5.", "SYSTEM DESIGN AND ARCHITECTURE", "47"],
    ["5.1", "SYSTEM ARCHITECTURE", "47"],
    ["5.2", "DATA FLOW DIAGRAM", "47"],
    ["5.3", "USE CASE DIAGRAM", "48"],
    ["5.4", "ACTIVITY DIAGRAM", "48"],
    ["5.5", "SEQUENCE DIAGRAM", "49"],
    ["5.6", "CLASS DIAGRAM", "49"],
    ["5.7", "DATABASE DESIGN", "49"],
    ["6.", "IMPLEMENTATION", "50"],
    ["6.1", "DEVELOPMENT ENVIRONMENT", "51"],
    ["6.2", "DATA PROCESSING", "53"],
    ["6.3", "FEATURE PROCESSING", "54"],
    ["6.4", "MODEL IMPLEMENTATION", "55"],
    ["6.5", "MODEL TRAINING", "56"],
    ["6.6", "MODEL SAVING", "57"],
    ["6.7", "DEPLOYMENT", "58"],
    ["6.8", "USER INTERFACE", "59"],
    ["7.", "RESULTS AND DISCUSSIONS", "63"],
    ["7.1", "EXPERIMENTAL SETUP", "63"],
    ["7.2", "EVALUATION METRICS", "63"],
    ["7.3", "MODEL PERFORMANCE", "63"],
    ["7.4", "COMPARATIVE ANALYSIS", "64"],
    ["7.5", "PREDICTION RESULTS", "64"],
    ["7.6", "VISUALIZATION RESULTS", "65"],
    ["7.7", "DISCUSSION", "65"],
    ["8.", "CONCLUSION AND FUTURE ENHANCEMENT", "69"],
    ["8.1", "SUMMARY OF THE WORK", "69"],
    ["8.2", "KEY CONTRIBUTIONS", "70"],
    ["8.3", "ACHIEVEMENT OF OBJECTIVES", "70"],
    ["8.4", "LIMITATIONS", "71"],
    ["8.5", "FUTURE ENHANCEMENTS", "71"],
    ["", "REFERENCES", "72"],
    ["", "APPENDIX", "74"],
    ["", "PO & PSO ATTAINMENT", "87"],
    ["", "RESEARCH PAPER", "90"]
]

# Table 2: List of Figures (22 rows x 3 cols)
TABLE_2 = [
    ["Figure No.", "Title", "Page No."],
    ["Figure 1.1", "Inbound Lead Qualification Drop vs Response Latency Benchmark", "2"],
    ["Figure 1.2", "Missed Lead Detector & Recovery Suite High-Level Architecture", "13"],
    ["Figure 2.1", "Taxonomy of Inbound Email Filtering and Intent Recognition Systems", "17"],
    ["Figure 2.2", "Email Classification Drift: 3-Class Confusion vs 7-Class Boundary Separation", "21"],
    ["Figure 4.1", "End-to-End Inbound Lead Ingestion, Classification, and Recovery Pipeline", "35"],
    ["Figure 4.2", "Category Distribution across Curated 2,270 Email Training Corpus", "37"],
    ["Figure 4.3", "Text Cleaning, Tokenization, and Stop-Word Removal Sequence", "38"],
    ["Figure 4.4", "TF-IDF N-gram Term Frequency Distribution Across Classes", "39"],
    ["Figure 4.5", "N-Gram Vocabulary Weights for Commercial vs Non-Commercial Categories", "40"],
    ["Figure 4.6", "Intent Classification & Urgency Priority Mapping Decision Tree", "41"],
    ["Figure 4.7", "Real-Time SLA Countdown & Automatic Breach Transition State Machine", "44"],
    ["Figure 4.8", "Model Convergence Curve and Loss Minimization During Training", "46"],
    ["Figure 5.1", "Multi-Tier Enterprise System Architecture and Component Routing", "47"],
    ["Figure 5.2", "Data Flow Diagram (Level 0 Context, Level 1 Process, Level 2 Pipeline)", "48"],
    ["Figure 5.3", "Use Case Diagram for Sales Representatives and Operations Admins", "48"],
    ["Figure 5.4", "Activity Workflow Diagram of Inbound Lead Ingestion & Recovery", "49"],
    ["Figure 5.5", "Sequence Diagram of Gmail API Sync, NLP Processing, and DB Commit", "49"],
    ["Figure 5.6", "Class Diagram of EmailProcessor, SLAChecker, and FollowUpGenerator", "50"],
    ["Figure 6.1", "FastAPI / Streamlit / Next.js Decoupled Microservice Architecture", "58"],
    ["Figure 6.2", "LeadGuard Operations Dashboard with Lead Queue and SLA Status", "60"],
    ["Figure 6.3", "Automated Follow-Up Review and One-Click Recovery Dispatch Modal", "61"]
]

# Table 3: List of Tables (16 rows x 3 cols)
TABLE_3 = [
    ["Table No.", "Title", "Page No."],
    ["Table 2.1", "Comprehensive Survey of Email Classification & Lead Recovery Methodologies", "21"],
    ["Table 3.1", "Hardware Requirements Specification", "31"],
    ["Table 3.2", "Software Requirements Specification", "31"],
    ["Table 3.3", "Feature Comparison: Traditional Email Filters vs LeadGuard AI Suite", "33"],
    ["Table 4.1", "Dataset Category Distribution and Vocabulary Characteristics (2,270 Emails)", "37"],
    ["Table 4.2", "Top Discriminant N-gram Features and Learned TF-IDF Class Weights", "40"],
    ["Table 4.3", "Hyperparameter Configuration and Grid Search Optimization Parameters", "47"],
    ["Table 5.1", "SQLite Database Schema: Emails and Activity Audit Log Tables", "50"],
    ["Table 7.1", "Quantitative Benchmark Comparison Across ML Classification Backbones", "63"],
    ["Table 7.2", "Cross-Category Classification Report and Validation Metrics", "64"],
    ["Table 7.3", "Per-Class Precision, Recall, F1-Score, and Support Breakdown", "65"],
    ["Table 7.4", "Ablation Study: Progressive Pipeline Architecture Enhancements", "66"],
    ["Table 7.5", "Computational Complexity, Inference Latency, and Throughput Benchmarks", "67"],
    ["Table 8.1", "Project Objective Achievement and Target Attainment Matrix", "70"],
    ["Table A.1", "Program Outcomes (PO) & PSO Attainment Mapping", "87"]
]

# Table 4: Symbols & Abbreviations (19 rows x 2 cols)
TABLE_4 = [
    ["Acronym", "Expansion"],
    ["AI", "Artificial Intelligence"],
    ["ML", "Machine Learning"],
    ["NLP", "Natural Language Processing"],
    ["TF-IDF", "Term Frequency - Inverse Document Frequency"],
    ["SLA", "Service Level Agreement"],
    ["CRM", "Customer Relationship Management"],
    ["SDR", "Sales Development Representative"],
    ["LR", "Logistic Regression"],
    ["SVM", "Support Vector Machine"],
    ["REST", "Representational State Transfer"],
    ["API", "Application Programming Interface"],
    ["JSON", "JavaScript Object Notation"],
    ["OAuth2", "Open Authorization 2.0 Standard"],
    ["SQL", "Structured Query Language"],
    ["UI / UX", "User Interface / User Experience"],
    ["CAC", "Customer Acquisition Cost"],
    ["LTV", "Customer Lifetime Value"],
    ["IMAP", "Internet Message Access Protocol"]
]
